version: '3'

services:
    myproj_redis:
      image: redis:4.0.6-alpine
      ports:
        - "6379:6379"
        - "6060:6379"
      volumes:
        - ./redis:/data  
    myproj_db:
        image: mongo:3.6
        ports:
            - "27017:27017"
    myproj_api:
      build: "./"
      ports:
        - "5057:5057"
      depends_on:
        - myproj_redis
      links:
        - myproj_redis  
        - myproj_db
    myproj_worker:
      image: myproj:latest
      command: rq worker --url redis://myproj_redis:6379 my_queue
      depends_on:
        - myproj_redis
      links:
        - myproj_redis